<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>OpenExamSuite.ExamIO</AssemblyName>
    <RootNamespace>OpenExamSuite.Shared</RootNamespace>
    <NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" />
    <PackageReference Include="protobuf-net" />
    <PackageReference Include="System.Formats.Nrbf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Logging\Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\fonts\NotoSans-VariableFont.ttf" />
    <EmbeddedResource Include="Resources\fonts\NotoSans-VariableFont-Italic.ttf" />
  </ItemGroup>
</Project>
