<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>OpenExamSuite.ExamIO</AssemblyName>
    <RootNamespace>OpenExamSuite.Shared</RootNamespace>
    <NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="PDFsharp" />
    <PackageReference Include="protobuf-net" />
    <PackageReference Include="System.Formats.Nrbf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Logging\Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\Apps\Simulator\Assets\Fonts\IBMPlexSans-Regular.ttf">
      <LogicalName>OpenExamSuite.Shared.Resources.fonts.IBMPlexSans-Regular.ttf</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\Apps\Simulator\Assets\Fonts\IBMPlexSans-Bold.ttf">
      <LogicalName>OpenExamSuite.Shared.Resources.fonts.IBMPlexSans-Bold.ttf</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\Apps\Simulator\Assets\Fonts\IBMPlexSans-Italic.ttf">
      <LogicalName>OpenExamSuite.Shared.Resources.fonts.IBMPlexSans-Italic.ttf</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
