<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>OpenExamSuite.ExamIO</AssemblyName>
    <RootNamespace>OpenExamSuite.Shared</RootNamespace>
    <NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.4" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.7" />
    <PackageReference Include="System.Formats.Nrbf" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Logging\Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\fonts\NotoSans-VariableFont.ttf" />
    <EmbeddedResource Include="Resources\fonts\NotoSans-VariableFont-Italic.ttf" />
  </ItemGroup>
</Project>
