namespace OpenExamSuite.Creator.Localization;

public static class Strings
{
    private static readonly Dictionary<string, string> Values = new(StringComparer.OrdinalIgnoreCase)
    {
        ["AppName"] = "Open Exam Creator",
        ["Screen_Creator"] = "Creator",
        ["Menu_File"] = "_File",
        ["Menu_New"] = "_New",
        ["Menu_Open"] = "_Open",
        ["Menu_Save"] = "_Save",
        ["Menu_SaveAs"] = "Save _As",
        ["Menu_Import"] = "_Import JSON",
        ["Menu_ExportJson"] = "Export _JSON",
        ["Menu_ExportXml"] = "E_xport XML",
        ["Menu_ExportPdf"] = "Export _PDF",
        ["Menu_TryExam"] = "_Try this exam",
        ["Menu_Exit"] = "E_xit",
        ["Menu_Edit"] = "_Edit",
        ["Menu_Undo"] = "_Undo",
        ["Menu_Redo"] = "_Redo",
        ["Menu_Theme"] = "_Theme",
        ["Theme_System"] = "_System",
        ["Theme_Light"] = "_Light",
        ["Theme_Dark"] = "_Dark",
        ["Theme_Toggle"] = "Toggle theme",
        ["Menu_Help"] = "_Help",
        ["Menu_About"] = "_About",
        ["Menu_License"] = "_License",
        ["Menu_Changelog"] = "_Changelog",
        ["Title_Unsaved"] = "Unsaved changes",
        ["Message_Unsaved"] = "Save changes to the current exam?",
        ["Button_Save"] = "Save",
        ["Button_DontSave"] = "Don't save",
        ["Button_Cancel"] = "Cancel",
        ["Toast_Saved"] = "Saved",
        ["Toast_NoSimulator"] = "Simulator not found",
        ["Dialog_OpenTitle"] = "Open exam",
        ["Dialog_SaveTitle"] = "Save exam",
        ["Dialog_ImportTitle"] = "Import JSON exam",
        ["Dialog_ExportJsonTitle"] = "Export JSON exam",
        ["Dialog_ExportXmlTitle"] = "Export XML exam",
        ["Dialog_ExportPdfTitle"] = "Export PDF exam",
        ["Validation_NoCorrectAnswer"] = "No correct answer",
        ["Validation_FewerThanTwoOptions"] = "Fewer than 2 options",
        ["Validation_EmptyQuestionText"] = "Empty question text",
        ["Validation_DuplicateSectionName"] = "Duplicate section name",
        ["Outline_Exam"] = "Exam",
        ["Outline_Search"] = "Search outline",
        ["Outline_AddSection"] = "Add section",
        ["Outline_AddQuestion"] = "Add question",
        ["Editor_Properties"] = "Exam properties",
        ["Editor_Section"] = "Section",
        ["Editor_Question"] = "Question",
        ["Editor_Title"] = "Title",
        ["Editor_Code"] = "Code",
        ["Editor_Instructions"] = "Instructions",
        ["Editor_PassMark"] = "Pass mark (%)",
        ["Editor_TimeLimit"] = "Time limit (min)",
        ["Editor_HideAnswers"] = "Hide answers in Practice and PDF export",
        ["Editor_SectionName"] = "Section name",
        ["Editor_QuestionText"] = "Question text",
        ["Editor_Explanation"] = "Explanation",
        ["Editor_SingleAnswer"] = "Single answer",
        ["Editor_MultipleAnswer"] = "Multiple answer",
        ["Editor_AddImage"] = "Add image",
        ["Editor_RemoveImage"] = "Remove image",
        ["Editor_AddOption"] = "Add option",
        ["Preview_Title"] = "Live preview",
        ["Validation_Title"] = "Problems",
        ["Recovery_Title"] = "Recover unsaved work?",
        ["Recovery_Message"] = "A newer autosaved copy was found. Recover it?"
    };

    public static string Get(string key) => Values.TryGetValue(key, out var value) ? value : key;
}
