<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>OpenExamSuite.Core</AssemblyName>
    <RootNamespace>OpenExamSuite.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
</Project>
