<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
    <AssemblyName>OpenExamSuite.Shared</AssemblyName>
    <RootNamespace>OpenExamSuite.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logging\Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Storage\Resources\fonts\NotoSans-VariableFont.ttf">
      <Link>Resources\fonts\NotoSans-VariableFont.ttf</Link>
      <LogicalName>OpenExamSuite.Shared.Resources.fonts.NotoSans-VariableFont.ttf</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Storage\Resources\fonts\NotoSans-VariableFont-Italic.ttf">
      <Link>Resources\fonts\NotoSans-VariableFont-Italic.ttf</Link>
      <LogicalName>OpenExamSuite.Shared.Resources.fonts.NotoSans-VariableFont-Italic.ttf</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
