<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
    <AssemblyName>OpenExamSuite.Shared</AssemblyName>
    <RootNamespace>OpenExamSuite.Shared</RootNamespace>
    <AssemblyVersion>4.0.0</AssemblyVersion>
    <Version>4.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
    <PackageReference Include="System.Formats.Nrbf" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logging\Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\fonts\NotoSans-VariableFont-Italic.ttf" />
    <EmbeddedResource Include="Resources\fonts\NotoSans-VariableFont.ttf" />
  </ItemGroup>
</Project>
