<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="10.0.0" />
    <PackageVersion Include="coverlet.msbuild" Version="10.0.0" />
    <PackageVersion Include="LiteDB" Version="5.0.21" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="PDFsharp" Version="6.2.4" />
    <PackageVersion Include="protobuf-net" Version="3.2.56" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageVersion Include="System.Drawing.Common" Version="10.0.7" />
    <PackageVersion Include="System.Formats.Nrbf" Version="10.0.7" />
    <PackageVersion Include="System.Windows.Forms.DataVisualization" Version="1.0.0-prerelease.20110.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
